diphthong_conversion = {
    "a'a" : "a",
    "a'e" : "ai",
    "a'i" : "ai",
    "ai" : "ai",
    "a'o" : "au",
    "a'u" : "au",
    "au" : "au",
    "e'e" : "e",
    "e'i" : "e",
    "ei" : "e",
    "e'o" : "eu",
    "e'u" : "eu",
    "i'e" : "i",
    "i'i" : "i",
    "e'a" : "ia",
    "i'a" : "ia",
    "i'o" : "io",
    "i'u" : "io",
    "o'o" : "o",
    "o'u" : "o",
    "o'e" : "oi",
    "o'i" : "oi",
    "oi" : "oi",
    "u'o" : "u",
    "u'u" : "u",
    "o'a" : "ua",
    "u'a" : "ua",
    "u'e" : "ue",
    "u'i" : "ue",
}

coda_conversion = dict(zip('bpfvdtgkxcjszlmnr', 'bbffddgggsssslfnr'))