import math
from src.substring_positions import substring_positions

diphthong_conversion = {
    "a'a" : "a",
    "a'e" : "ai",
    "a'i" : "ai",
    "ai" : "ai",
    "a'o" : "au",
    "a'u" : "au",
    "au" : "au",
    "e'e" : "e",
    "e'i" : "e",
    "ei" : "e",
    "e'o" : "eu",
    "e'u" : "eu",
    "i'e" : "i",
    "i'i" : "i",
    "e'a" : "ia",
    "i'a" : "ia",
    "i'o" : "io",
    "i'u" : "io",
    "o'o" : "o",
    "o'u" : "o",
    "o'e" : "oi",
    "o'i" : "oi",
    "oi" : "oi",
    "u'o" : "u",
    "u'u" : "u",
    "o'a" : "ua",
    "u'a" : "ua",
    "u'e" : "ue",
    "u'i" : "ue",
}

coda_conversion = dict(zip('bpfvdtgkxcjszlmnr', 'bbbbddgggsssslmnr'))

def stage1(row):

    form = row['cmavo_rafsi_1']
    shape = row['form_shape_1']
    pos = row['rafsi_pos_1']
    gismu = row['gismu']
    gismu_shape = row['gismu_shape']
    pos_tendency = row['pos_tendency']  

    # Process forms

    if not form: 
        form, shape = gismu[:4], 'CACC'

    elif shape == 'CAC':
        pass

    elif 'AA' in shape:
        # CA(')A > CA(')A CCA(')A
        n = 2 if shape[1] == 'C' else 1     # 2 if CC-, 1 if C-
        p = -1 if shape[-1] == 'C' else 0   # -1 if -C (ends in consonant), else 0

        if shape[1] == 'C':
            a, b, c = form[:2], form[2:-1], form[-1]
        else:
            a, b, c = form[:1], form[1:], ''

        b2 = diphthong_conversion.get(b, b)

        if len(b2) == 2:
            if gismu_shape == 'CCACA' and pos_tendency != 'fin':
                form = f'{gismu[:2]}{b2}{c}'
                shape = 'CCAA'
            else:
                form = f'{a}{b2}{c}'
        
        elif len(b2) == 1:

            forms_secondary = {row['cmavo_rafsi_2'], row['cmavo_rafsi_3']}
            excluded_forms = row['excluded']
            if excluded_forms:
                forms_secondary.update(excluded_forms.split(' '))

            if gismu_shape == 'CCACA':
                trigraphs = (f'{gismu[:1]}{gismu[2:4]}', gismu[1:4])    # 134, 234
            elif gismu_shape == 'CACCA':
                trigraphs = (gismu[:3], f'{gismu[:2]}{gismu[3]}')   # 123, 124

            form = f'{a}{b2}_'
            for p in forms_secondary:
                for q in trigraphs:
                    if p == q:
                        form = q
                        break
            shape = 'CAC'

    if shape.startswith('CC'):
        # CCA, CCAC: xl > kl, xr > kr
        if form[0] == 'h':
            b = form[1:]
            form = f'k{b}'

    if shape.endswith('CC'):
        a, b = form[:-2], form[-2:].replace('x', 'k')
        form = f'{a}{b}' 

    if shape.endswith('AC'):
        a, b = form[:-1], form[-1]
        b2 = coda_conversion.get(b, b)
        form = f'{a}{b2}'             

    return form

def stage2(row):

    # Chiefly to reduce homomorphy among forms generated by stage1

    form = row['current_form']
    shape = row['current_form_shape']
    gismu = row['gismu']
    gismu_shape = row['gismu_shape']
    pos_tendency = row['pos_tendency']  

    if row['final_count'] > 1:

        if shape == 'CAC' and gismu_shape == 'CCACA' and pos_tendency == 'ini':
            form, shape = gismu[:4], 'CCAC'

    return form
    